//! Graph informational benchmarks: PERF-06 (`log_page_500`), PERF-07 (`graph_lanes_only`),
//! PERF-11 (`graph_index_full`) and PERF-16 (`log_search_sha`, `log_search_text`).
//!
//! Measured repository: `GITMINI_BENCH_REPO` if defined, otherwise fixture `perf-100k` (`tests/fixtures/build.sh perf-100k`,
//! in `target/fixtures/`) if it exists, otherwise a synthetic repository of 20,000 commits generated by `git fast-import`.
//! `GITMINI_BENCH_COMMITS=100000` forces the synthetic repository of 100,000 commits (`GenSpec::fx100k`).
//!
//!     cargo bench -p gitmini-core --bench log

#[path = "../tests/graphgen/mod.rs"]
mod graphgen;

use std::path::{Path, PathBuf};
use std::sync::Arc;
use std::time::{Duration, Instant};

use criterion::{BatchSize, Criterion, criterion_group, criterion_main};
use gitmini_core::read::log::{self, LogPageArgs, LogSearchArgs, SearchField};
use gitmini_core::state::RepoHandle;
use graphgen::*;

struct Dataset {
    path: PathBuf,
    label: String,
    _keep: Option<TestRepo>,
}

fn workspace() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join("../..")
}

fn dataset() -> Dataset {
    if let Some(p) = std::env::var_os("GITMINI_BENCH_REPO") {
        return Dataset {
            path: PathBuf::from(p),
            label: "GITMINI_BENCH_REPO".into(),
            _keep: None,
        };
    }
    let commits: Option<usize> = std::env::var("GITMINI_BENCH_COMMITS")
        .ok()
        .and_then(|v| v.parse().ok());
    if commits == Some(100_000) {
        let (with_cg, _) = shared_fx100k();
        return Dataset {
            path: with_cg,
            label: "fx100k synthetic".into(),
            _keep: None,
        };
    }
    let fx = workspace().join("target/fixtures/perf-100k/repo");
    if commits.is_none() && fx.join(".git").exists() {
        return Dataset {
            path: fx,
            label: "perf-100k".into(),
            _keep: None,
        };
    }
    let spec = GenSpec {
        commits: commits.unwrap_or(20_000),
        branches: 100,
        merges: 400,
        tags: 10,
        remotes: true,
        ..GenSpec::default()
    };
    let repo = synthetic(&spec);
    write_commit_graph(&repo.path);
    Dataset {
        path: repo.path.clone(),
        label: format!("synthetic {} commits", spec.commits),
        _keep: Some(repo),
    }
}

/// Even repository without commit-graph file (copy).
fn without_commit_graph(path: &Path) -> Option<TestRepo> {
    let tmp = tempfile::tempdir().ok()?;
    let dest = tmp.path().canonicalize().ok()?.join("repo");
    copy_dir(path, &dest);
    remove_commit_graph(&dest);
    Some(TestRepo { tmp, path: dest })
}

fn fresh_handle(
    path: &Path,
) -> (
    Arc<gitmini_core::AppState>,
    Arc<RepoHandle>,
    tempfile::TempDir,
) {
    let cfg = tempfile::tempdir().unwrap();
    let state = gitmini_core::AppState::with_git(
        gitmini_core::AppConfig::for_tests(cfg.path().to_path_buf()),
        Arc::new(gitmini_core::events::CollectSink::default()),
        gitmini_core::state::GitInfo::detect(),
    );
    let id = state.next_repo_id();
    let repo = gitmini_core::repo::open_handle(state.shared.clone(), id, path).unwrap();
    (state, repo, cfg)
}

fn page(repo: &Arc<RepoHandle>, start: Option<u32>, limit: u32) -> usize {
    let a = LogPageArgs {
        repo_id: repo.id,
        cursor: None,
        start_row: start,
        around_oid: None,
        limit: Some(limit),
    };
    log::log_page_blocking(repo, &a).unwrap().rows.len()
}

fn search(
    repo: &Arc<RepoHandle>,
    query: &str,
    fields: Option<Vec<SearchField>>,
    limit: u32,
) -> usize {
    let a = LogSearchArgs {
        repo_id: repo.id,
        query: query.into(),
        fields,
        limit: Some(limit),
    };
    log::log_search_blocking(repo, &a).unwrap().matches.len()
}

fn benches(c: &mut Criterion) {
    let ds = dataset();
    eprintln!("data set: {} ({})", ds.label, ds.path.display());
    let (_state, repo, _cfg) = fresh_handle(&ds.path);
    log::build_index_blocking(&repo).unwrap();
    let (rows, memory) = {
        let g = repo.graph.read().unwrap();
        (g.row_count(), g.memory_bytes())
    };
    eprintln!("{rows} lines, index {:.1} Mo", memory as f64 / 1_048_576.0);

    // PERF-06 / B6 : 500 line page (mid-page, last page from a checkpoint)
    let mut g = c.benchmark_group("log_page_500");
    g.bench_function("milieu", |b| {
        b.iter(|| page(&repo, Some(rows as u32 / 2), 500))
    });
    g.bench_function("derniere_page", |b| {
        b.iter(|| page(&repo, Some(rows.saturating_sub(500) as u32), 500))
    });
    g.bench_function("premiere_page", |b| b.iter(|| page(&repo, None, 500)));
    g.finish();

    // PERF-07: recalculation of the lanes on an existing index (< 15 ms per 100k, )
    let mut g = c.benchmark_group("graph_lanes");
    g.bench_function("graph_lanes_only", |b| {
        b.iter(|| log::bench_lanes_only(&repo))
    });
    g.bench_function("order_and_lanes", |b| {
        b.iter(|| log::bench_order_and_lanes(&repo))
    });
    g.finish();

    // PERF-11 / B3: complete construction (track + order + lanes), with and without commit-graph
    let mut g = c.benchmark_group("graph_index_full");
    g.sample_size(10);
    g.bench_function("avec_commit_graph", |b| {
        b.iter_batched(
            || fresh_handle(&ds.path),
            |(_s, r, _c)| log::build_index_blocking(&r).unwrap(),
            BatchSize::PerIteration,
        )
    });
    if let Some(nocg) = without_commit_graph(&ds.path) {
        g.bench_function("sans_commit_graph", |b| {
            b.iter_batched(
                || fresh_handle(&nocg.path),
                |(_s, r, _c)| log::build_index_blocking(&r).unwrap(),
                BatchSize::PerIteration,
            )
        });
    }
    g.finish();

    // B2 (backend part): from opening up to 500 lines served
    let mut g = c.benchmark_group("open_first_page");
    g.sample_size(10);
    g.bench_function("avec_commit_graph", |b| {
        b.iter_custom(|iters| {
            let mut total = Duration::ZERO;
            for _ in 0..iters {
                let (_s, r, _c) = fresh_handle(&ds.path);
                let start = Instant::now();
                log::spawn_index_build(r.clone());
                assert_eq!(page(&r, None, 500), 500.min(rows));
                total += start.elapsed();
                assert!(log::wait_index_complete(&r, Duration::from_secs(120)));
            }
            total
        })
    });
    g.finish();

    // PERF-16 / B15
    let some = {
        let a = LogPageArgs {
            repo_id: repo.id,
            cursor: None,
            start_row: Some(rows as u32 / 3),
            around_oid: None,
            limit: Some(1),
        };
        log::log_page_blocking(&repo, &a).unwrap().rows[0]
            .oid
            .clone()
    };
    let mut g = c.benchmark_group("log_search");
    g.bench_function("log_search_sha", |b| {
        b.iter(|| search(&repo, &format!("sha:{}", &some[..7]), None, 1_000))
    });
    g.sample_size(10);
    // query for distributed matches: search query (perf-100k) or commit 1 (synthetic game)
    let spread = if search(&repo, "msg:search query", None, 1) > 0 {
        "msg:search query"
    } else {
        "msg:commit 1"
    };
    g.bench_function("log_search_text_premiers_50", |b| {
        b.iter(|| search(&repo, spread, None, 50))
    });
    g.bench_function("log_search_author_premiers_50", |b| {
        b.iter(|| {
            search(&repo, "author:alice", None, 50).max(search(&repo, "author:karine", None, 50))
        })
    });
    g.bench_function("log_search_text_sans_resultat", |b| {
        b.iter(|| search(&repo, "msg:zzz-introuvable", None, 1_000))
    });
    g.bench_function("log_search_author_sans_resultat", |b| {
        b.iter(|| search(&repo, "author:zzz-introuvable", None, 1_000))
    });
    g.finish();

    // §2.4: ahead/behind branches at upstream, empty cache then full
    let pairs: Vec<(gix::ObjectId, gix::ObjectId)> = {
        let r = repo.thread_repo();
        let mut v = Vec::new();
        for reference in r.references().unwrap().local_branches().unwrap().flatten() {
            let name = reference.name().as_bstr().to_string();
            let short = name.trim_start_matches("refs/heads/");
            if let Ok(mut remote) =
                r.find_reference(format!("refs/remotes/origin/{short}").as_str())
                && let Ok(b) = remote.peel_to_id()
            {
                v.push((reference.id().detach(), b.detach()));
            }
        }
        v
    };
    if !pairs.is_empty() {
        eprintln!("{} branches with upstream", pairs.len());
        let mut g = c.benchmark_group("ahead_behind");
        g.sample_size(10);
        g.bench_function("cache_vide", |b| {
            b.iter_batched(
                || log::reset_ahead_behind_cache(&repo),
                |_| {
                    pairs
                        .iter()
                        .map(|(a, b)| {
                            log::ahead_behind(&repo, *a, *b).map(|v| v.0).unwrap_or(0) as usize
                        })
                        .sum::<usize>()
                },
                BatchSize::PerIteration,
            )
        });
        g.bench_function("cache_plein", |b| {
            b.iter(|| {
                pairs
                    .iter()
                    .map(|(a, b)| {
                        log::ahead_behind(&repo, *a, *b).map(|v| v.0).unwrap_or(0) as usize
                    })
                    .sum::<usize>()
            })
        });
        g.finish();
    }

    // §5.3: 20 commits added to a tip, then updated index (< 5 ms out of lanes)
    if let Some(inc) = incremental_dataset(&ds.path) {
        let (_s, r, _c) = fresh_handle(&inc.repo.path);
        log::build_index_blocking(&r).unwrap();
        let ref_file = inc.repo.path.join(".git/refs/heads/incremental");
        let mut g = c.benchmark_group("incremental_fetch_20");
        g.sample_size(20);
        g.bench_function("refresh_index", |b| {
            b.iter_custom(|iters| {
                let mut total = Duration::ZERO;
                for _ in 0..iters {
                    std::fs::write(&ref_file, format!("{}\n", inc.tip)).unwrap();
                    let start = Instant::now();
                    log::refresh_index(&r);
                    total += start.elapsed();
                    std::fs::remove_file(&ref_file).unwrap();
                    log::refresh_index(&r);
                }
                total
            })
        });
        g.finish();
    }
}

struct Incremental {
    repo: TestRepo,
    tip: String,
}

/// Copy of repository with 20 commits in a string whose branch is removed (objects remain).
fn incremental_dataset(path: &Path) -> Option<Incremental> {
    let tmp = tempfile::tempdir().ok()?;
    let dest = tmp.path().canonicalize().ok()?.join("repo");
    copy_dir(path, &dest);
    let base = git(&dest, &["rev-parse", "HEAD"]);
    let tip = append_chain(&dest, "incremental", &base, 20, 4_000_000_000);
    git(&dest, &["update-ref", "-d", "refs/heads/incremental"]);
    Some(Incremental {
        repo: TestRepo { tmp, path: dest },
        tip,
    })
}

criterion_group! {
    name = log_benches;
    config = Criterion::default().warm_up_time(Duration::from_secs(1)).measurement_time(Duration::from_secs(3));
    targets = benches
}
criterion_main!(log_benches);
