//! Informative Reading Benchmarks: PERF-08 (`status_clean`), PERF-17 / PERF-18 (`status_dirty`,
//! `status_untracked_20k`), PERF-12 (`commit_details`), PERF-13 (`diff_file`), plus `refs_list_300`.
//!
//! Measured repositories: `perf-100k` and `perf-100k-dirty` fixtures if they exist in `target/fixtures/` (generated by
//! `tests/fixtures/build.sh`), if not synthetic repositories cached in `target/bench-read/`. `GITMINI_BENCH_REPO`
//! replaces the repository of `status_clean` / `commit_details`.
//!
//!     cargo bench -p gitmini-core --bench read

use std::path::{Path, PathBuf};
use std::process::{Command, Stdio};
use std::sync::Arc;

use criterion::{BatchSize, Criterion, criterion_group, criterion_main};
use gitmini_core::events::NullSink;
use gitmini_core::read::diff::{CommitDetailsArgs, DiffFileArgs, commit_details, diff_file};
use gitmini_core::read::refs::refs_list;
use gitmini_core::read::status::{RepoArgs, status_snapshot};
use gitmini_core::repo::{RepoOpenArgs, repo_open};
use gitmini_core::state::{AppConfig, AppState, GitInfo, RepoHandle};
use gitmini_core::types::DiffSource;

fn workspace() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join("../..")
}

fn git_bin() -> PathBuf {
    let usr = PathBuf::from("/usr/bin/git");
    if usr.is_file() {
        usr
    } else {
        PathBuf::from("git")
    }
}

fn git(dir: &Path, args: &[&str]) -> String {
    let out = Command::new(git_bin())
        .current_dir(dir)
        .args(args)
        .env("GIT_AUTHOR_NAME", "Bench")
        .env("GIT_AUTHOR_EMAIL", "bench@gitmini")
        .env("GIT_COMMITTER_NAME", "Bench")
        .env("GIT_COMMITTER_EMAIL", "bench@gitmini")
        .stdin(Stdio::null())
        .output()
        .expect("git");
    assert!(
        out.status.success(),
        "git {args:?} : {}",
        String::from_utf8_lossy(&out.stderr)
    );
    String::from_utf8_lossy(&out.stdout).trim_end().to_string()
}

fn cache_dir(name: &str) -> PathBuf {
    let dir = workspace().join("target/bench-read").join(name);
    std::fs::create_dir_all(&dir).unwrap();
    dir
}

/// Synthetic repository: `files` files tracked in 100 folders, 30 commits.
fn synthetic_clean(files: usize) -> PathBuf {
    let dir = cache_dir(&format!("clean-{files}"));
    if dir.join(".git").exists() {
        return dir;
    }
    git(&dir, &["init", "-q", "-b", "main"]);
    for i in 0..files {
        let p = dir.join(format!("d{:03}/f{i:05}.txt", i % 100));
        std::fs::create_dir_all(p.parent().unwrap()).unwrap();
        std::fs::write(p, format!("file {i}\n").repeat(20)).unwrap();
    }
    git(&dir, &["add", "-A"]);
    git(&dir, &["commit", "-q", "-m", "base"]);
    for c in 0..30 {
        for k in 0..5 {
            let i = (c * 7 + k * 13) % files;
            std::fs::write(
                dir.join(format!("d{:03}/f{i:05}.txt", i % 100)),
                format!("v{c} {i}\n").repeat(30),
            )
            .unwrap();
        }
        git(&dir, &["add", "-A"]);
        git(&dir, &["commit", "-q", "-m", &format!("commit {c}")]);
    }
    dir
}

/// 5,000 files tracked, 1,000 modified, 20,000 untracked in 200 folders (like `FX-100K-DIRTY`).
fn synthetic_dirty() -> PathBuf {
    let dir = cache_dir("dirty");
    if dir.join(".git").exists() {
        return dir;
    }
    git(&dir, &["init", "-q", "-b", "main"]);
    for i in 0..5000 {
        let p = dir.join(format!("d{:03}/f{i:05}.txt", i % 100));
        std::fs::create_dir_all(p.parent().unwrap()).unwrap();
        std::fs::write(p, format!("file {i}\n").repeat(20)).unwrap();
    }
    git(&dir, &["add", "-A"]);
    git(&dir, &["commit", "-q", "-m", "base"]);
    for i in 0..1000 {
        std::fs::write(
            dir.join(format!("d{:03}/f{i:05}.txt", i % 100)),
            "modified\n".repeat(21),
        )
        .unwrap();
    }
    for i in 0..20_000 {
        let p = dir.join(format!("untracked/u{:03}/n{i:05}.txt", i % 200));
        std::fs::create_dir_all(p.parent().unwrap()).unwrap();
        std::fs::write(p, "x\n").unwrap();
    }
    dir
}

/// 50 files from 10 Kio to 1 Mio, commits then modified in the middle (diff `unstaged`, never cached).
fn synthetic_diff_files() -> PathBuf {
    let dir = cache_dir("difffiles");
    if dir.join(".git").exists() {
        return dir;
    }
    git(&dir, &["init", "-q", "-b", "main"]);
    for i in 0..50 {
        let lines = 200 + i * 400; // ≈ 10 Kio … 1 Mio
        let body: String = (0..lines)
            .map(|l| format!("{l:06} line of {i} file with some text\n"))
            .collect();
        std::fs::write(dir.join(format!("big{i:02}.txt")), body).unwrap();
    }
    git(&dir, &["add", "-A"]);
    git(&dir, &["commit", "-q", "-m", "base"]);
    for i in 0..50 {
        let lines = 200 + i * 400;
        let body: String = (0..lines)
            .map(|l| {
                if l % 97 == 0 {
                    format!("LIGNE MODIFIEE {l}\n")
                } else {
                    format!("{l:06} line of {i} file with some text\n")
                }
            })
            .collect();
        std::fs::write(dir.join(format!("big{i:02}.txt")), body).unwrap();
    }
    dir
}

/// 300 branches at upstream (`origin/*`) on 3,000 commits.
fn synthetic_refs_300() -> PathBuf {
    let dir = cache_dir("refs300");
    if dir.join(".git").exists() {
        return dir;
    }
    git(&dir, &["init", "-q", "-b", "main"]);
    let origin = dir.join("../refs300-origin.git");
    std::fs::create_dir_all(&origin).unwrap();
    git(&origin, &["init", "-q", "--bare", "-b", "main"]);
    git(&dir, &["remote", "add", "origin", origin.to_str().unwrap()]);
    for i in 0..300 {
        std::fs::write(dir.join("f.txt"), format!("v{i}\n")).unwrap();
        git(&dir, &["add", "-A"]);
        git(&dir, &["commit", "-q", "-m", &format!("c{i}")]);
        git(&dir, &["branch", &format!("b{i:03}")]);
    }
    git(&dir, &["push", "-q", "origin", "--all"]);
    for i in 0..300 {
        git(
            &dir,
            &[
                "branch",
                "-q",
                &format!("--set-upstream-to=origin/b{i:03}"),
                &format!("b{i:03}"),
            ],
        );
    }
    // Like `FX-100K` (generated by fast-import): refs packaged, not 600 loose refs files
    git(&dir, &["pack-refs", "--all"]);
    dir
}

fn runtime() -> tokio::runtime::Runtime {
    tokio::runtime::Builder::new_multi_thread()
        .enable_all()
        .build()
        .unwrap()
}

fn open(rt: &tokio::runtime::Runtime, path: &Path) -> (Arc<AppState>, Arc<RepoHandle>) {
    let cfg = AppConfig::for_tests(std::env::temp_dir().join("gitmini-bench-read-config"));
    let state = AppState::with_git(cfg, Arc::new(NullSink), GitInfo::detect());
    let info = rt
        .block_on(repo_open(
            &state,
            RepoOpenArgs {
                path: path.to_string_lossy().into_owned(),
            },
        ))
        .expect("repo_open");
    let repo = state.repo(info.id).unwrap();
    (state, repo)
}

fn clean_repo() -> PathBuf {
    if let Some(p) = std::env::var_os("GITMINI_BENCH_REPO") {
        return PathBuf::from(p);
    }
    let fx = workspace().join("target/fixtures/perf-100k/repo");
    if fx.join(".git").exists() {
        fx
    } else {
        synthetic_clean(5000)
    }
}

fn status_clean(c: &mut Criterion) {
    let rt = runtime();
    let (_s, repo) = open(&rt, &clean_repo());
    c.bench_function("status_clean", |b| {
        b.iter(|| rt.block_on(status_snapshot(&repo)).unwrap())
    });
}

fn status_dirty(c: &mut Criterion) {
    let rt = runtime();
    let fx = workspace().join("target/fixtures/perf-100k-dirty/repo");
    let path = if fx.join(".git").exists() {
        fx
    } else {
        synthetic_dirty()
    };
    let (_s, repo) = open(&rt, &path);
    let snap = rt.block_on(status_snapshot(&repo)).unwrap();
    eprintln!(
        "status_dirty: {} inputs, truncated = {}",
        snap.files.len(),
        snap.truncated
    );
    let mut g = c.benchmark_group("status_dirty");
    g.sample_size(20);
    g.bench_function("status_dirty", |b| {
        b.iter(|| rt.block_on(status_snapshot(&repo)).unwrap())
    });
    g.finish();
}

fn status_untracked_20k(c: &mut Criterion) {
    let rt = runtime();
    let fx = workspace().join("target/fixtures/untracked-20k/repo");
    if !fx.join(".git").exists() {
        eprintln!(
            "status_untracked_20k: `untracked-20k` fixture absent (tests/fixtures/build.sh untracked-20k), ignored"
        );
        return;
    }
    let (_s, repo) = open(&rt, &fx);
    let mut g = c.benchmark_group("status_untracked_20k");
    g.sample_size(20);
    g.bench_function("status_untracked_20k", |b| {
        b.iter(|| rt.block_on(status_snapshot(&repo)).unwrap())
    });
    g.finish();
}

fn commit_details_bench(c: &mut Criterion) {
    let rt = runtime();
    let path = clean_repo();
    let (state, repo) = open(&rt, &path);
    // 100 commits "at random" (fixed seed) among the last 5,000
    let all: Vec<String> = git(&path, &["rev-list", "--max-count=5000", "HEAD"])
        .lines()
        .map(str::to_string)
        .collect();
    let mut x: u64 = 0x9E37_79B9_7F4A_7C15;
    let picks: Vec<String> = (0..100)
        .map(|_| {
            x = x
                .wrapping_mul(6364136223846793005)
                .wrapping_add(1442695040888963407);
            all[(x >> 33) as usize % all.len()].clone()
        })
        .collect();
    let id = repo.id;
    let mut g = c.benchmark_group("commit_details");
    g.sample_size(20);
    g.bench_function("commit_details_100_random_cold_cache", |b| {
        b.iter_batched(
            || *repo.cache.lock().unwrap() = Default::default(),
            |_| {
                for oid in &picks {
                    rt.block_on(commit_details(
                        &state,
                        CommitDetailsArgs {
                            repo_id: id,
                            oid: oid.clone(),
                            against: None,
                        },
                    ))
                    .unwrap();
                }
            },
            BatchSize::PerIteration,
        )
    });
    g.finish();
}

fn diff_file_bench(c: &mut Criterion) {
    let rt = runtime();
    let (state, repo) = open(&rt, &synthetic_diff_files());
    let id = repo.id;
    let mut g = c.benchmark_group("diff_file");
    g.sample_size(10);
    g.bench_function("diff_file_50_files_10k_to_1mio", |b| {
        b.iter(|| {
            for i in 0..50 {
                rt.block_on(diff_file(
                    &state,
                    DiffFileArgs {
                        repo_id: id,
                        path: format!("big{i:02}.txt"),
                        source: DiffSource::Unstaged,
                        force: None,
                    },
                ))
                .unwrap();
            }
        })
    });
    g.finish();
}

fn refs_list_300(c: &mut Criterion) {
    let rt = runtime();
    let (state, repo) = open(&rt, &synthetic_refs_300());
    let id = repo.id;
    let mut g = c.benchmark_group("refs_list_300");
    g.sample_size(20);
    g.bench_function("refs_list_300", |b| {
        b.iter(|| {
            rt.block_on(refs_list(&state, RepoArgs { repo_id: id }))
                .unwrap()
        })
    });
    g.finish();
}

/// Informative breakdown of `refs_list_300` (printed, non-criterion): repository rereading, refs course,
/// resolution of 300 upstreams.
fn refs_breakdown(_c: &mut Criterion) {
    let rt = runtime();
    let (_state, repo) = open(&rt, &synthetic_refs_300());
    let runs = 20u32;
    let time = |label: &str, f: &dyn Fn()| {
        f();
        let t = std::time::Instant::now();
        for _ in 0..runs {
            f();
        }
        eprintln!("refs_list_300 / {label} : {:?}", t.elapsed() / runs);
    };
    time("fresh_repo (reload)", &|| {
        gitmini_core::read::refs::fresh_repo(&repo).unwrap();
    });
    let git = gitmini_core::read::refs::fresh_repo(&repo).unwrap();
    time("iteration + peel de 300 branches", &|| {
        let platform = git.references().unwrap();
        for r in platform.local_branches().unwrap().flatten() {
            let mut r = r;
            let _ = r.peel_to_id();
        }
    });
    let names: Vec<gix::refs::FullName> = {
        let platform = git.references().unwrap();
        platform
            .local_branches()
            .unwrap()
            .flatten()
            .map(|r| r.name().to_owned())
            .collect()
    };
    time("resolve_upstream x300", &|| {
        for n in &names {
            let _ = gitmini_core::read::refs::resolve_upstream(&git, n.as_ref());
        }
    });
}

criterion_group!(
    benches,
    refs_breakdown,
    status_clean,
    status_dirty,
    status_untracked_20k,
    commit_details_bench,
    diff_file_bench,
    refs_list_300
);
criterion_main!(benches);
