//! Help with graph  tests: repositories synthetics generated by `git fast-import`, comparison with the
//! true CLI `git` (`/usr/bin/git` as a priority, cf. docs/architecture.md), opening a repository and log pages.
//! Shared by `tests/graph.rs`, `tests/log.rs` and `benches/log.rs` (`#[path]`).
#![allow(dead_code)]

use std::io::Write;
use std::path::{Path, PathBuf};
use std::process::{Command, Stdio};
use std::sync::Arc;
use std::time::Duration;

use gitmini_core::events::CollectSink;
use gitmini_core::read::log::{self, LogPageArgs, wait_index_complete};
use gitmini_core::state::{AppConfig, AppState, GitInfo, RepoHandle};
use gitmini_core::types::{GraphRow, LogPage};

pub fn git_program() -> PathBuf {
    // GITMINI_TEST_GIT (e.g. a compiled git 2.30, tests/git-compat/README.md) takes precedence over `/usr/bin/git`.
    if let Some(explicit) = std::env::var_os("GITMINI_TEST_GIT") {
        return PathBuf::from(explicit);
    }
    let usr = PathBuf::from("/usr/bin/git");
    if usr.is_file() {
        usr
    } else {
        PathBuf::from("git")
    }
}

fn git_command(dir: &Path) -> Command {
    let mut c = Command::new(git_program());
    c.current_dir(dir)
        .env("LC_ALL", "C")
        .env("TZ", "UTC")
        .env("GIT_CONFIG_NOSYSTEM", "1")
        .env("GIT_TERMINAL_PROMPT", "0")
        .env("GIT_AUTHOR_NAME", "Fixture Bot")
        .env("GIT_AUTHOR_EMAIL", "bot@fixtures.gitmini")
        .env("GIT_COMMITTER_NAME", "Fixture Bot")
        .env("GIT_COMMITTER_EMAIL", "bot@fixtures.gitmini")
        .env("HOME", dir.join(".gitmini-test-home"))
        .env_remove("GIT_DIR")
        .env_remove("GIT_WORK_TREE")
        .env_remove("GIT_INDEX_FILE")
        .stdin(Stdio::null());
    c
}

/// Standard output of `git <args>` (without the last line jump); fails the test if git fails.
pub fn git(dir: &Path, args: &[&str]) -> String {
    let out = git_command(dir).args(args).output().expect("lancer git");
    assert!(
        out.status.success(),
        "git {args:?} failed: {}\n{}",
        out.status,
        String::from_utf8_lossy(&out.stderr)
    );
    String::from_utf8_lossy(&out.stdout)
        .trim_end_matches('\n')
        .to_string()
}

/// `git <args>` with a fixed commit date (commits created by hand in the tests).
pub fn git_at(dir: &Path, time: i64, args: &[&str]) -> String {
    let date = format!("@{time} +0000");
    let out = git_command(dir)
        .env("GIT_AUTHOR_DATE", &date)
        .env("GIT_COMMITTER_DATE", &date)
        .args(args)
        .output()
        .expect("lancer git");
    assert!(
        out.status.success(),
        "git {args:?} failed: {}\n{}",
        out.status,
        String::from_utf8_lossy(&out.stderr)
    );
    String::from_utf8_lossy(&out.stdout)
        .trim_end_matches('\n')
        .to_string()
}

pub fn git_lines(dir: &Path, args: &[&str]) -> Vec<String> {
    git(dir, args).lines().map(str::to_string).collect()
}

// - - repositories
/// Temporary repository (file deleted from drop).
pub struct TestRepo {
    pub tmp: tempfile::TempDir,
    pub path: PathBuf,
}

impl TestRepo {
    pub fn init() -> Self {
        let tmp = tempfile::tempdir().expect("tmpdir");
        let root = tmp.path().canonicalize().unwrap();
        let path = root.join("repo");
        std::fs::create_dir_all(&path).unwrap();
        git(&path, &["init", "-q", "-b", "main", "."]);
        for (k, v) in [
            ("user.name", "Fixture Bot"),
            ("user.email", "bot@fixtures.gitmini"),
            ("commit.gpgsign", "false"),
            ("tag.gpgsign", "false"),
            ("gc.auto", "0"),
            ("maintenance.auto", "false"),
        ] {
            git(&path, &["config", k, v]);
        }
        TestRepo { tmp, path }
    }

    pub fn git(&self, args: &[&str]) -> String {
        git(&self.path, args)
    }

    pub fn git_at(&self, time: i64, args: &[&str]) -> String {
        git_at(&self.path, time, args)
    }

    /// Deemed empty on a given date; returns the oid.
    pub fn commit_at(&self, time: i64, msg: &str) -> String {
        self.git_at(time, &["commit", "-q", "--allow-empty", "-m", msg]);
        self.git(&["rev-parse", "HEAD"])
    }
}

/// Recursive copy of a folder.
pub fn copy_dir(src: &Path, dst: &Path) {
    std::fs::create_dir_all(dst).unwrap();
    for entry in std::fs::read_dir(src).unwrap() {
        let entry = entry.unwrap();
        let to = dst.join(entry.file_name());
        let ty = entry.file_type().unwrap();
        if ty.is_dir() {
            copy_dir(&entry.path(), &to);
        } else if ty.is_symlink() {
            let target = std::fs::read_link(entry.path()).unwrap();
            #[cfg(unix)]
            std::os::unix::fs::symlink(target, &to).unwrap();
        } else {
            std::fs::copy(entry.path(), &to).unwrap();
        }
    }
}

fn workspace_root() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("../..")
        .canonicalize()
        .unwrap()
}

// - - generation by fast-import
#[derive(Clone, Debug)]
pub struct GenSpec {
    pub commits: usize,
    /// Branches en plus de `main`.
    pub branches: usize,
    /// Merges with two parents (approximative).
    pub merges: usize,
    /// Octopus merges with three parents.
    pub octopus: usize,
    pub tags: usize,
    pub seed: u64,
    pub base_time: i64,
    /// A commit on `n` takes the date of the previous one (ex æquo; 0 = never).
    pub tie_every: usize,
    /// A commit on `n` is older than its predecessor (clock drive; 0 = never).
    pub skew_every: usize,
    pub authors: usize,
    pub files: usize,
    /// One `refs/remotes/origin/<branche>` ref per branch (various advance/delay).
    pub remotes: bool,
}

impl Default for GenSpec {
    fn default() -> Self {
        Self {
            commits: 2_000,
            branches: 20,
            merges: 100,
            octopus: 0,
            tags: 5,
            seed: 42,
            base_time: 1_700_000_000,
            tie_every: 0,
            skew_every: 0,
            authors: 5,
            files: 50,
            remotes: false,
        }
    }
}

impl GenSpec {
    /// Approximation de `FX-100K`  : 100 000 commits, 300 branches, 1 000 merges, 30 tags.
    pub fn fx100k() -> Self {
        Self {
            commits: 100_000,
            branches: 299,
            merges: 1_000,
            tags: 30,
            files: 5_000,
            remotes: true,
            ..Self::default()
        }
    }
}

struct Rng(u64);

impl Rng {
    fn next(&mut self) -> u64 {
        // xorshift64*
        self.0 ^= self.0 >> 12;
        self.0 ^= self.0 << 25;
        self.0 ^= self.0 >> 27;
        self.0.wrapping_mul(0x2545_F491_4F6C_DD1D)
    }
    fn below(&mut self, n: usize) -> usize {
        (self.next() % n as u64) as usize
    }
    fn chance(&mut self, num: usize, den: usize) -> bool {
        self.below(den) < num
    }
}

const AUTHORS: [(&str, &str); 6] = [
    ("Alice Martin", "alice@example.com"),
    ("Bob Durand", "bob@example.com"),
    ("Carol Petit", "carol@example.com"),
    ("Dave Leroy", "dave@example.com"),
    ("Eve Moreau", "eve@example.com"),
    ("Frank Roux", "frank@example.com"),
];

fn branch_name(slot: usize) -> String {
    if slot == 0 {
        "main".into()
    } else {
        format!("feature/b{slot}")
    }
}

/// Creates a repository not bare in `dir` (already created) with `spec`. Returns the number of commits written.
pub fn generate(dir: &Path, spec: &GenSpec) -> usize {
    git(dir, &["init", "-q", "-b", "main", "."]);
    let mut child = git_command(dir)
        .args(["fast-import", "--quiet", "--done"])
        .stdin(Stdio::piped())
        .stdout(Stdio::null())
        .spawn()
        .expect("git fast-import");
    let mut out = std::io::BufWriter::with_capacity(1 << 20, child.stdin.take().unwrap());
    let mut rng = Rng(spec.seed.max(1));

    let n_slots = spec.branches + 1;
    let mut tips: Vec<Option<usize>> = vec![None; n_slots];
    let mut history: Vec<Vec<usize>> = vec![Vec::new(); n_slots];
    let mut next_branch = 1usize;
    let mut time = spec.base_time;
    let merge_p = (spec.merges, spec.commits.max(1));
    let octo_p = (spec.octopus, spec.commits.max(1));
    let mut written = 0usize;
    let stride = (spec.commits / (spec.branches + 1)).max(1);

    for i in 1..=spec.commits {
        // which branch receives the commit
        let slot = if next_branch <= spec.branches && i >= next_branch * stride {
            let s = next_branch;
            next_branch += 1;
            s
        } else if rng.chance(2, 5) {
            0
        } else {
            let live: Vec<usize> = (0..n_slots).filter(|&s| tips[s].is_some()).collect();
            if live.is_empty() {
                0
            } else {
                live[rng.below(live.len())]
            }
        };
        let mut parents: Vec<usize> = Vec::new();
        match tips[slot] {
            Some(t) => parents.push(t),
            None => {
                // new branch: from an existing commit (or root for the very first)
                if i > 1 {
                    parents.push(rng.below(i - 1) + 1);
                }
            }
        }
        // merges: other tips as additional parents
        let want_octo = rng.chance(octo_p.0, octo_p.1);
        let want_merge = want_octo || rng.chance(merge_p.0, merge_p.1);
        if want_merge && !parents.is_empty() {
            let extra = if want_octo { 2 } else { 1 };
            for _ in 0..extra {
                let live: Vec<usize> = (0..n_slots)
                    .filter(|&s| s != slot && tips[s].is_some())
                    .collect();
                if live.is_empty() {
                    break;
                }
                let t = tips[live[rng.below(live.len())]].unwrap();
                if !parents.contains(&t) {
                    parents.push(t);
                }
            }
        }
        // dates
        if spec.tie_every > 0 && i % spec.tie_every == 0 {
            // same date as the previous
        } else if spec.skew_every > 0 && i % spec.skew_every == 0 {
            time -= 90;
        } else {
            time += 60;
        }
        let (an, ae) = AUTHORS[rng.below(spec.authors.clamp(1, AUTHORS.len()))];
        let msg = if i % 7 == 0 {
            format!(
                "commit {i}: detailed topic\n\nCorps of message number {i}\n with a second line.\n"
            )
        } else {
            format!("commit {i}\n")
        };
        write!(out, "commit refs/heads/{}\nmark :{i}\n", branch_name(slot)).unwrap();
        write!(
            out,
            "author {an} <{ae}> {time} +0000\ncommitter {an} <{ae}> {time} +0000\n"
        )
        .unwrap();
        write!(out, "data {}\n{msg}", msg.len()).unwrap();
        if let Some(p0) = parents.first() {
            writeln!(out, "from :{p0}").unwrap();
        }
        for p in parents.iter().skip(1) {
            writeln!(out, "merge :{p}").unwrap();
        }
        let content = format!("content {i}\n");
        write!(
            out,
            "M 100644 inline f{:05}.txt\ndata {}\n{content}\n",
            i % spec.files.max(1),
            content.len()
        )
        .unwrap();
        tips[slot] = Some(i);
        history[slot].push(i);
        written += 1;
    }
    // tags: half annotated, half light
    for t in 0..spec.tags {
        let mark = rng.below(spec.commits) + 1;
        if t % 2 == 0 {
            let msg = format!("tag v{t}\n");
            write!(out, "tag v{t}.0\nfrom :{mark}\ntagger Alice Martin <alice@example.com> {time} +0000\ndata {}\n{msg}", msg.len()).unwrap();
        } else {
            write!(out, "reset refs/tags/v{t}.0\nfrom :{mark}\n\n").unwrap();
        }
    }
    // remotes : trois formes (identique, en retard, divergent)
    if spec.remotes {
        for slot in 0..n_slots {
            let Some(tip) = tips[slot] else { continue };
            let target = match rng.below(3) {
                0 => tip,
                1 => history[slot][rng.below(history[slot].len())],
                _ => rng.below(spec.commits) + 1,
            };
            write!(
                out,
                "reset refs/remotes/origin/{}\nfrom :{target}\n\n",
                branch_name(slot)
            )
            .unwrap();
        }
    }
    writeln!(out, "done").unwrap();
    out.flush().unwrap();
    drop(out);
    assert!(child.wait().unwrap().success(), "git fast-import failed");
    git(dir, &["config", "user.name", "Fixture Bot"]);
    git(dir, &["config", "user.email", "bot@fixtures.gitmini"]);
    git(dir, &["config", "gc.auto", "0"]);
    git(dir, &["config", "maintenance.auto", "false"]);
    git(dir, &["checkout", "-q", "-f", "main"]);
    written
}

/// Synthetic repository in a temporary folder.
pub fn synthetic(spec: &GenSpec) -> TestRepo {
    let tmp = tempfile::tempdir().expect("tmpdir");
    let path = tmp.path().canonicalize().unwrap().join("repo");
    std::fs::create_dir_all(&path).unwrap();
    generate(&path, spec);
    TestRepo { tmp, path }
}

pub fn write_commit_graph(dir: &Path) {
    git(dir, &["commit-graph", "write", "--reachable"]);
}

pub fn remove_commit_graph(dir: &Path) {
    let p = dir.join(".git/objects/info/commit-graph");
    let _ = std::fs::remove_file(p);
    let _ = std::fs::remove_dir_all(dir.join(".git/objects/info/commit-graphs"));
}

// ── ouverture

pub struct Opened {
    pub state: Arc<AppState>,
    pub repo: Arc<RepoHandle>,
    _cfg: tempfile::TempDir,
}

/// Opens `path` like `repo_open` (without watcher) and starts building the index in the background task.
pub fn open(path: &Path) -> Opened {
    let cfg = tempfile::tempdir().unwrap();
    let state = AppState::with_git(
        AppConfig::for_tests(cfg.path().to_path_buf()),
        Arc::new(CollectSink::default()),
        GitInfo::detect(),
    );
    let id = state.next_repo_id();
    let repo =
        gitmini_core::repo::open_handle(state.shared.clone(), id, path).expect("open_handle");
    state.insert_repo(repo.clone());
    log::spawn_index_build(repo.clone());
    Opened {
        state,
        repo,
        _cfg: cfg,
    }
}

/// Open and wait for the full index.
pub fn open_complete(path: &Path) -> Opened {
    let o = open(path);
    assert!(
        wait_index_complete(&o.repo, Duration::from_secs(300)),
        "index non complet"
    );
    o
}

//
pub fn page_args(repo: &RepoHandle) -> LogPageArgs {
    LogPageArgs {
        repo_id: repo.id,
        cursor: None,
        start_row: None,
        around_oid: None,
        limit: None,
    }
}

pub fn fetch_page(
    repo: &Arc<RepoHandle>,
    cursor: Option<String>,
    start_row: Option<u32>,
    limit: Option<u32>,
) -> LogPage {
    let mut a = page_args(repo);
    a.cursor = cursor;
    a.start_row = start_row;
    a.limit = limit;
    log::log_page_blocking(repo, &a).expect("log_page")
}

/// All log lines, page after page (cursors).
pub fn all_rows(repo: &Arc<RepoHandle>, limit: u32) -> Vec<GraphRow> {
    let mut out = Vec::new();
    let mut cursor = None;
    loop {
        let page = fetch_page(repo, cursor.take(), None, Some(limit));
        out.extend(page.rows);
        match page.next_cursor {
            Some(c) => cursor = Some(c),
            None => break,
        }
    }
    out
}

/// Oids in the order of `git log --date-order` with the same tips as gitmini (HEAD, branches, remotes, tags).
pub fn git_date_order(dir: &Path) -> Vec<String> {
    git_lines(
        dir,
        &[
            "log",
            "--date-order",
            "--format=%H",
            "HEAD",
            "--branches",
            "--remotes",
            "--tags",
        ],
    )
}

/// Add `n` commits empty chain on `branch` (created or advanced) from `from_oid`, growing dates
/// from `time0`. Returns the oid of the last. For incremental insertion tests.
pub fn append_chain(dir: &Path, branch: &str, from_oid: &str, n: usize, time0: i64) -> String {
    let mut child = git_command(dir)
        .args(["fast-import", "--quiet", "--done", "--force"])
        .stdin(Stdio::piped())
        .stdout(Stdio::null())
        .spawn()
        .expect("git fast-import");
    let mut out = std::io::BufWriter::new(child.stdin.take().unwrap());
    for i in 1..=n {
        let t = time0 + i as i64 * 60;
        let msg = format!("chain {branch} {i}\n");
        write!(out, "commit refs/heads/{branch}\nmark :{i}\nauthor Fixture Bot <bot@fixtures.gitmini> {t} +0000\n").unwrap();
        write!(
            out,
            "committer Fixture Bot <bot@fixtures.gitmini> {t} +0000\ndata {}\n{msg}",
            msg.len()
        )
        .unwrap();
        if i == 1 {
            writeln!(out, "from {from_oid}").unwrap();
        } else {
            writeln!(out, "from :{}", i - 1).unwrap();
        }
        out.write_all(b"\n").unwrap();
    }
    writeln!(out, "done").unwrap();
    out.flush().unwrap();
    drop(out);
    assert!(child.wait().unwrap().success(), "git fast-import failed");
    git(dir, &["rev-parse", &format!("refs/heads/{branch}")])
}

// - - repository of 100 000 commits shared (measures)
/// `FX-100K` approached (`GenSpec::fx100k`), generated once in `target/graph-tests/` and then reused; returns the
/// repository folder (with commit-graph) and its copy without commit-graph. Use the `perf-100k` fixture of the
/// repository if it already exists.
pub fn shared_fx100k() -> (PathBuf, PathBuf) {
    let root = workspace_root();
    let base = root.join("target/graph-tests/fx100k");
    let with_cg = base.join("repo");
    let without = base.join("repo-nocg");
    if !with_cg.join(".git/objects/info/commit-graph").exists() {
        let _ = std::fs::remove_dir_all(&base);
        std::fs::create_dir_all(&with_cg).unwrap();
        generate(&with_cg, &GenSpec::fx100k());
        write_commit_graph(&with_cg);
        git(&with_cg, &["gc", "-q", "--no-prune"]);
        write_commit_graph(&with_cg);
    }
    if !without.join(".git").exists() {
        copy_dir(&with_cg, &without);
        remove_commit_graph(&without);
    }
    (with_cg, without)
}

/// repository of 30,000 commits (read only), generated once in `target/graph-tests/` and then reused.
pub fn shared_big() -> PathBuf {
    let dir = workspace_root().join("target/graph-tests/big30k/repo");
    if !dir.join(".git/objects/info/commit-graph").exists() {
        let _ = std::fs::remove_dir_all(&dir);
        std::fs::create_dir_all(&dir).unwrap();
        let spec = GenSpec {
            commits: 30_000,
            branches: 120,
            merges: 1_500,
            octopus: 30,
            tags: 12,
            ..GenSpec::default()
        };
        generate(&dir, &spec);
        write_commit_graph(&dir);
    }
    dir
}
