// File generated by `cargo run -p gitmini-core --example gen_types`: do not change.
/* eslint-disable */
// This file has been generated by Specta. Do not edit this file manually.
export type AllMarker = "all";

/**  Typed error returned by any IPC command. `message` is in English and displayable as is. */
export type AppError = {
	code: ErrorCode,
	message: string,
	details?: { [key in string]: unknown } | null,
};

export type AppInfo = {
	version: string,
	git: GitInfoDto | null,
	gitError: GitError | null,
	initialPath: string | null,
	e2e: boolean,
	/**  `settings.json` was corrupted on startup: renamed `.bak`, default values (toast information). */
	settingsRecovered: boolean,
};

export type AuthorRef = {
	name: string,
	email: string,
};

export type BranchCompare = {
	branchOid: string,
	targetOid: string,
	mergeBase: string | null,
	ahead: number,
	behind: number,
	commits: CompareCommit[],
	merges: number,
	pushed: number,
	dirty: boolean,
	defaultMergeMessage: string,
};

export type BranchInfo = {
	name: string,
	fullRef: string,
	oid: string,
	isHead: boolean,
	upstream: BranchUpstream | null,
	tipDate: number,
};

export type BranchUpstream = {
	ref: string,
	remote: string,
	ahead: number | null,
	behind: number | null,
	gone: boolean,
};

export type ChangeKind = "added" | "modified" | "deleted" | "renamed" | "copied" | "typechange" | "untracked";

export type ChangeKindEv = "refs" | "index" | "worktree" | "head" | "stash";

export type CommitDetails = {
	oid: string,
	parents: string[],
	tree: string,
	author: Signature,
	committer: Signature,
	message: string,
	files: FileChange[],
	truncated: boolean,
};

export type CompareCommit = {
	oid: string,
	summary: string,
	pushed: boolean,
};

export type ConflictKind = "both-modified" | "both-added" | "both-deleted" | "added-by-us" | "added-by-them" | "deleted-by-us" | "deleted-by-them";

export type ConflictView = "markers" | "ours" | "theirs";

export type DiffLine = {
	kind: DiffLineKind,
	oldNo: number | null,
	newNo: number | null,
	text: string,
};

export type DiffLineKind = "ctx" | "add" | "del" | "noeol";

export type DiffSource = { kind: "unstaged" } | { kind: "staged" } | { kind: "commit"; oid: string; parent: number | null } | { kind: "range"; from: string; to: string } | { kind: "stash"; oid: string; part: StashPart } | { kind: "conflict"; view: ConflictView };

export type DiffStats = {
	added: number,
	removed: number,
};

export type ErrorCode = "CONFLICT" | "UNRESOLVED_CONFLICTS" | "DIRTY_WORKTREE" | "UNTRACKED_WOULD_BE_OVERWRITTEN" | "INDEX_CONFLICT" | "AUTH_REQUIRED" | "REJECTED_NON_FF" | "NETWORK" | "GIT_FAILED" | "IDENTITY_MISSING" | "NOT_FOUND" | "NOT_A_REPO" | "UNSUPPORTED_REPO_FORMAT" | "ALREADY_EXISTS" | "NOT_MERGED" | "BUSY" | "CANCELLED" | "INVALID_ARGUMENT" | "STALE" | "DETACHED_HEAD" | "UNSUPPORTED_MERGES" | "UNDO_UNAVAILABLE" | "GIT_MISSING" | "GIT_TOO_OLD";

export type FileChange = {
	path: string,
	oldPath: string | null,
	change: ChangeKind,
	additions: number | null,
	deletions: number | null,
	binary: boolean,
	submodule: boolean | null,
};

export type FileDiff = {
	path: string,
	oldPath: string | null,
	oldMode: number | null,
	newMode: number | null,
	binary: boolean,
	tooLarge: TooLarge | null,
	oldSize: number | null,
	newSize: number | null,
	hunks: Hunk[],
	stats: DiffStats,
	/**  xxh3 of the text patch (garde `STALE { what: "diff" }`) */
	hash: string,
	submodule: SubmoduleDiff | null,
	lfsPointer: boolean | null,
};

export type FileStatus = {
	path: string,
	oldPath: string | null,
	staged: ChangeKind | null,
	unstaged: ChangeKind | null,
	conflict: ConflictKind | null,
	oldMode: number | null,
	newMode: number | null,
	submodule: boolean | null,
	nonUtf8: boolean | null,
};

export type GitError = "GIT_MISSING" | "GIT_TOO_OLD";

export type GitInfoDto = {
	path: string,
	version: string,
};

export type GithubLoginPoll = {
	status: GithubPollStatus,
	interval: number,
	login: string | null,
};

export type GithubLoginStart = {
	loginId: string,
	userCode: string,
	verificationUri: string,
	expiresIn: number,
	interval: number,
};

export type GithubPollStatus = "pending" | "slow-down" | "success" | "expired" | "denied";

export type GithubRepo = {
	fullName: string,
	cloneUrl: string,
	sshUrl: string,
	private: boolean,
	fork: boolean,
	description: string | null,
	updatedAt: string,
	defaultBranch: string,
};

export type GithubStatus = {
	loggedIn: boolean,
	login: string | null,
};

export type GraphRow = {
	oid: string,
	parents: string[],
	summary: string,
	author: number,
	time: number,
	refs: RefLabel[],
	lane: number,
	color: number,
	kind: RowKind,
	stashIndex: number | null,
	/**
	 *  Commit listed in `<common_dir>/shallow` (border of a superficial repository): only case where the front displays
	 *  `graph-shallow-marker`. False for "normal" root and stash.
	 */
	shallow: boolean,
	/**  flattened: [fromLane, toLane, color, flags] × n ; flags bit0 = low half, bit1 = dotted */
	edges: number[],
};

export type HeadInfo = {
	branch: string | null,
	oid: string | null,
	detached: boolean,
	unborn: boolean,
};

export type Hunk = {
	header: string,
	oldStart: number,
	oldLines: number,
	newStart: number,
	newLines: number,
	lines: DiffLine[],
};

export type Identity = {
	name: string,
	email: string,
	scope: IdentityScope,
};

export type IdentityScope = "global" | "local" | "other";

export type LogMatch = {
	oid: string,
	row: number,
};

export type LogPage = {
	rows: GraphRow[],
	authors: AuthorRef[],
	start: number,
	total: number | null,
	nextCursor: string | null,
	epoch: number,
	maxLanes: number,
	/**
	 *  Unreadable commits encountered during the journey (missing or corrupt object, 04 "In error case"): empty
	 *  when the history is complete. Each is a root of the graph; the front displays "Incomplete History:
	 *  objet <sha7> illisible ».
	 */
	missing: string[],
};

export type LogSearchResult = {
	matches: LogMatch[],
	truncated: boolean,
};

export type OpKind = "rebase" | "merge" | "cherry-pick" | "revert" | "am";

export type OpPhase = "running" | "conflict" | "stopped";

/**  Charge utile de `op:progress`. */
export type OpProgress = {
	opId: string,
	label: string,
	percent: number | null,
};

/**  Charge utile de `op:state`. */
export type OpStateEvent = {
	repoId: number,
	state: RepoOpState | null,
};

export type OpenTarget = { kind: "url"; url: string } | { kind: "file"; path: string; line: number | null };

/**  `paths: string[] | "all"` index commands. */
export type PathsOrAll = string[] | AllMarker;

export type RecentRepo = {
	path: string,
	name: string,
	/**  ISO 8601 */
	lastOpened: string,
};

export type RefLabel = {
	name: string,
	fullRef: string,
	kind: RefLabelKind,
	isHead: boolean,
};

export type RefLabelKind = "local" | "remote" | "tag" | 
/**  HEAD detached */
"head";

export type ReflogEntry = {
	index: number,
	oid: string,
	previous: string,
	message: string,
	time: number,
};

export type RefsHead = { kind: "branch"; name: string } | { kind: "detached"; oid: string } | { kind: "unborn"; name: string };

export type RefsSnapshot = {
	head: RefsHead,
	local: BranchInfo[],
	remote: RemoteBranchInfo[],
	tags: TagInfo[],
};

export type RemoteBranchInfo = {
	remote: string,
	name: string,
	fullRef: string,
	oid: string,
};

export type RemoteInfo = {
	name: string,
	fetchUrl: string,
	pushUrl: string,
	isGithub: boolean,
	githubSlug: string | null,
};

/**  Charge utile de `repo:changed`. */
export type RepoChanged = {
	repoId: number,
	kinds: ChangeKindEv[],
};

export type RepoInfo = {
	id: number,
	workdir: string,
	gitDir: string,
	commonDir: string,
	name: string,
	head: HeadInfo,
	opState: RepoOpState | null,
	identity: Identity | null,
	hasCommitGraph: boolean,
	isShallow: boolean,
	lfs: boolean,
};

export type RepoOpState = {
	kind: OpKind,
	phase: OpPhase,
	stopReason: StopReason | null,
	headName: string | null,
	onto: string | null,
	ontoLabel: string | null,
	incoming: string | null,
	step: number | null,
	total: number | null,
	stoppedAt: string | null,
	currentSummary: string | null,
	conflictedPaths: string[],
	autostash: boolean,
};

export type RowKind = "commit" | "stash";

export type Signature = {
	name: string,
	email: string,
	time: number,
	offsetMinutes: number,
};

export type StashEntry = {
	index: number,
	oid: string,
	message: string,
	branch: string | null,
	baseOid: string,
	hasIndex: boolean,
	hasUntracked: boolean,
	time: number,
};

export type StashFiles = {
	worktree: FileChange[],
	index: FileChange[],
	untracked: FileChange[],
};

export type StashPart = "worktree" | "index" | "untracked";

export type StatusSnapshot = {
	head: HeadInfo,
	files: FileStatus[],
	truncated: boolean,
	upstream: string | null,
	ahead: number | null,
	behind: number | null,
	/**  Degraded watcher mode of the worktree (limit inotify): the front rereads the status to the focus and then every 5 seconds. */
	watcherDegraded: boolean,
};

export type StopReason = "empty" | "blocked" | "stale";

export type SubmoduleDiff = {
	oldOid: string | null,
	newOid: string | null,
	dirty: boolean,
};

export type TagInfo = {
	name: string,
	fullRef: string,
	oid: string,
	targetOid: string,
	annotated: boolean,
};

export type TodoAction = "pick" | "reword" | "squash" | "fixup" | "drop";

export type TodoItem = {
	oid: string,
	action: TodoAction,
	message?: string | null,
};

export type TodoPreview = {
	base: string | null,
	head: string,
	items: TodoPreviewItem[],
};

export type TodoPreviewItem = {
	oid: string,
	shortOid: string,
	summary: string,
	message: string,
	author: string,
	pushed: boolean,
};

export type TooLarge = {
	bytes: number,
	lines: number,
	hardLimit: boolean,
};

export type UndoBlockReason = "empty" | "pushed" | "head-moved" | "ref-moved" | "op-in-progress" | "exists" | "object-missing";

export type UndoEntry = {
	id: string,
	kind: UndoKind,
	label: string,
	effect: string,
	refName: string | null,
	before: string | null,
	after: string | null,
	stashMessage: string | null,
	stashOid: string | null,
	upstreamRef: string | null,
	upstreamAtOp: string | null,
	pushed: boolean,
	time: number,
};

export type UndoKind = "commit" | "amend" | "merge" | "rebase" | "cherry-pick" | "revert" | "pull" | "branch-delete" | "stash-drop";

export type UndoStatus = {
	entry: UndoEntry | null,
	available: boolean,
	reason: UndoBlockReason | null,
	head: string | null,
};

export type WriteResult = {
	head: HeadInfo,
};
