//! Export TypeScript of contract types (`src/lib/ipc/types.ts`), via specta.
use specta::Types;

use crate::error::{AppError, ErrorCode};
use crate::events::{OpProgress, OpStateEvent, RepoChanged};
use crate::types::*;

/// All types of the IPC contract plus event and error payloads.
pub fn contract_types() -> Types {
    Types::default()
        .register::<AppError>()
        .register::<ErrorCode>()
        .register::<AppInfo>()
        .register::<RepoInfo>()
        .register::<RecentRepo>()
        .register::<WriteResult>()
        .register::<OpenTarget>()
        .register::<LogPage>()
        .register::<LogSearchResult>()
        .register::<CommitDetails>()
        .register::<StatusSnapshot>()
        .register::<DiffSource>()
        .register::<FileDiff>()
        .register::<RefsSnapshot>()
        .register::<ReflogEntry>()
        .register::<BranchCompare>()
        .register::<RepoOpState>()
        .register::<TodoPreview>()
        .register::<TodoItem>()
        .register::<StashEntry>()
        .register::<StashFiles>()
        .register::<RemoteInfo>()
        .register::<GithubStatus>()
        .register::<GithubLoginStart>()
        .register::<GithubLoginPoll>()
        .register::<GithubRepo>()
        .register::<UndoEntry>()
        .register::<UndoStatus>()
        .register::<RepoChanged>()
        .register::<OpProgress>()
        .register::<OpStateEvent>()
        .register::<crate::events::ChangeKindEv>()
        .register::<crate::write::PathsOrAll>()
}

pub fn export_to(path: &str) -> Result<(), String> {
    use specta_typescript::Typescript;
    Typescript::default()
        .header("// File generated by `cargo run -p gitmini-core --example gen_types`: do not change.\n/* eslint-disable */")
        .export_to(path, &contract_types(), specta_serde::Format)
        .map_err(|e| e.to_string())
}
